---
- name: Deploy Redis in a Docker container
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Pull Redis image from Docker Hub
      docker_image:
        name: redis
        source: pull

    - name: Run Redis container
      docker_container:
        name: redis_container
        image: redis
        state: started
        ports:
          - "6379:6379"

