---
- name: Deploy Nginx in a Docker container
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Pull Nginx image from Docker Hub
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        ports:
          - "80:80"

